"""SENSMOS_USE_TLS PoC — pre-build hook for the nodemcuv2_tls PlatformIO env.

The wolfssl/wolfssl PlatformIO package ships its own examples/configs/user_settings_
platformio.h as .../wolfssl/src/user_settings.h, and wolfssl/wolfcrypt/settings.h
auto-defines WOLFSSL_USER_SETTINGS and quoted-#include "user_settings.h" itself —
that resolves to the PACKAGE's bundled copy (found first on the include path), not
anything this project defines via -D build_flags. That bundled file is written for
ESP-IDF/ESP32 (ESP_LOGE, CONFIG_IDF_TARGET_*, sdkconfig.h) and is not valid for the
classic ESP8266 Arduino NONOS SDK framework this project targets — hence this hook
overwrites it with a minimal, ESP8266-appropriate config before every build. Runs
against the .pio/libdeps copy (regenerated by PlatformIO from the registry package on
every fresh install), never against anything committed to this repo.
"""
Import("env")
import os

CONTENT = """#ifndef WOLFSSL_USER_SETTINGS_H
#define WOLFSSL_USER_SETTINGS_H
/* Generated by esp8266/tools/patch_wolfssl_settings.py for SENSMOS_USE_TLS — do not
 * edit here, it is overwritten on every build. Edit that script instead. */

#define SINGLE_THREADED
#define NO_FILESYSTEM
#define NO_WRITEV
#define WOLFSSL_SMALL_STACK
/* Wznowienie sesji TLS 1.3 (ticket -> PSK 1-RTT). NO_SESSION_CACHE wycinalo
 * wolfSSL_get1_session/set_session CALKOWICIE (ssl_sess.c) — zamiast niego
 * mikro-cache, ktorego i tak nie uzywamy (runtime: SESS_CACHE_OFF w ws_tls.cpp;
 * sesje trzymamy sami przez refcount). Netto ~+24B .bss.
 * NO_PSK ZOSTAJE: kazda sciezka resumption jest gatowana
 * (HAVE_SESSION_TICKET || !NO_PSK) — sam ticket wystarcza, a zdjecie NO_PSK
 * kosztowaloby +1538B ENCRYPT_LEN (MAX_PSK_ID_LEN). Pulapka NST: bilet
 * przychodzi PO handshake'u — get1_session wolno wolac dopiero przy stop()
 * (wczesniejszy save + HaveUniqueSessionObj forkuje sesje i bilet przepada). */
#define HAVE_SESSION_TICKET
/* Klient-only device: server-side wolfSSL (w tym maszyneria ticketow serwera)
 * nigdy nie jest uzywany — bez tego define poszerzal CTX/SSL po wlaczeniu
 * HAVE_SESSION_TICKET. */
#define NO_WOLFSSL_SERVER
#define MICRO_SESSION_CACHE
#define SESSION_CACHE_DYNAMIC_MEM
#define NO_SESSION_CACHE_REF
#define NO_CLIENT_CACHE
#define WOLFSSL_NO_DEF_TICKET_ENC_CB
/* Bufory PSK-identity (Arrays.client_identity/server_hint + CTX.server_hint) sa
 * gatowane (HAVE_SESSION_TICKET || !NO_PSK) — sam ticket-define wciagal 2x1537B
 * do KAZDEGO ssl->arrays i +1.5KB do CTX (default MAX_PSK_ID_LEN=1536 pod TLS1.3).
 * W 1.3 identity PSK = bilet NST (~200-260B u nginx) — 384 starcza z zapasem;
 * wiekszy bilet => resumption pominiete i czysty pelny handshake (tls.c:13429). */
#define MAX_PSK_ID_LEN 384

#define NO_OLD_TLS
#define WOLFSSL_TLS13
#define HAVE_HKDF
#define WC_RSA_PSS
#define NO_DH
#define NO_PSK
#define NO_MD4
#define NO_RC4
#define NO_HC128
#define NO_RABBIT
#define NO_DES3
#define HAVE_ECC
#define ECC_USER_CURVES
#define HAVE_ECC256
#define HAVE_AESGCM
#define RSA_LOW_MEM

/* ESP8266 Arduino (NONOS SDK) has no BSD sockets layer — wolfio.h otherwise assumes
 * one exists for "ESP8266" targets. ws_tls.cpp supplies transport callbacks via
 * wolfSSL_CTX_SetIORecv/SetIOSend instead of the built-in socket implementation. */
#define WOLFSSL_USER_IO
#define WOLFSSL_NO_SOCK

/* SNI ("Server Name Indication") TLS extension — off by default in a minimal build;
 * wolfSSL_UseSNI() needs it explicitly. */
#define HAVE_SNI
#define HAVE_TLS_EXTENSIONS
/* Bez tego wolfSSL 5.7.2 buduje klienta TLS1.3, ktorego ClientHello NIE zawiera
 * supported_groups ANI key_share (oba gatowane w tls.c wylacznie na ten define,
 * zadny #error tego nie lapie) — serwer nie moze zrobic 1.3, downgraduje,
 * a klient przybity do 1.3 odrzuca to jako err -326 (VERSION_ERROR). */
#define HAVE_SUPPORTED_CURVES

/* Generyczny backend sp_int wymiaruje kazdy bignum pod RSA (4096 bit ≈ 1KB kazdy;
 * ecc_point zawiera 3) — ecc_make_pub_ex przy generowaniu key_share przekraczal
 * przejsciowo ~17KB wolnego bloku i padal z err -125 (MEMORY_E) [trace: EccMakeKey
 * -> ecc_make_pub_ex failed]. Dedykowane procedury SP dla P-256 (sp_c32.c) maja
 * male, stale bufory i sa duzo szybsze; RSA (weryfikacja certu) zostaje na
 * generycznym sp_int — pojedyncze ~4KB transienty, miesci sie. */
#define WOLFSSL_HAVE_SP_ECC
/* Samo SP_ECC zmniejsza generyczne SP_INT ponizej potrzeb RSA
 * (#error "SP_INT_BITS too small for WOLFSSL_MAX_RSA_BITS") — RSA tez na SP. */
#define WOLFSSL_HAVE_SP_RSA
/* BEZ WOLFSSL_SP_SMALL: wariant small robil pojedyncza weryfikacje ECDSA P-384
 * dluzsza niz ~6s nieprzerwanego liczenia -> HW WDT resetowal node w polowie
 * handshake'u (rst cause:2 w petli; nic nie karmi WDT wewnatrz sp_c32). Pelne SP
 * jest ~5-10x szybsze — kosztem flasha, ktorego jest pod dostatkiem. */

/* Pinning certyfikatu (ISRG Root X2): lancuch api.sensmos.com to ECDSA P-384 +
 * SHA-384 na KAZDYM poziomie (leaf podpisany ecdsa-with-SHA384 kluczem P-384 YE2)
 * — bez tych dwoch define'ow VERIFY_PEER nie ma czym zweryfikowac ani jednego
 * podpisu. P-384 liczy sie na generycznym sp_int (fallback WOLFSSL_SP_MATH_ALL;
 * NIE dodawac WOLFSSL_SP_384 — flash). Wymiana kluczy ZOSTAJE na P-256:
 * ws_tls.cpp ogranicza grupy przez wolfSSL_CTX_set_groups — HAVE_ECC384 bez tego
 * reklamowalby secp384r1 w key_share i keygen P-384 na generycznym sp_int
 * powtorzylby OOM err -125 (ecc_make_pub_ex), naprawiony wyzej przez SP_ECC. */
#define HAVE_ECC384
#define WOLFSSL_SHA384
/* Weryfikacja ECDSA P-384 na generycznym sp_int (SP_MATH_ALL fallback) zwracala
 * -155 ASN_SIG_CONFIRM_E na KAZDYM podpisie lancucha (trace: ConfirmSignature
 * failed przy "CA found") — dedykowana sciezka SP dla P-384 liczy poprawnie,
 * tak samo jak SP_ECC naprawilo P-256. Koszt: flash, zero DRAM. */
#define WOLFSSL_SP_384
/* Serwer wysyla lancuch az do cross-certa X2-podpisanego-przez-X1; domyslnie wolfSSL
 * weryfikuje KAZDY przedstawiony cert CA i pada z ASN_NO_SIGNER_E (-188), bo X1 nie
 * jest w store. ALT_CERT_CHAINS: wystarczy, ze lancuch domyka sie do zaufanego X2 —
 * nadmiarowy cross-cert jest ignorowany (zachowanie jak w OpenSSL/przegladarkach). */
#define WOLFSSL_ALT_CERT_CHAINS

/* wolfcrypt/test/test.c and benchmark.c are ESP-IDF example harnesses (ESP_LOGE,
 * sdkconfig.h) this project never calls — exclude them from the build entirely. */
#define NO_CRYPT_TEST
#define NO_CRYPT_BENCHMARK

#endif /* WOLFSSL_USER_SETTINGS_H */
"""

lib_dir = env.subst("$PROJECT_LIBDEPS_DIR")
pioenv = env.subst("$PIOENV")
target = os.path.join(lib_dir, pioenv, "wolfssl", "src", "user_settings.h")

if os.path.isdir(os.path.dirname(target)):
    with open(target, "w", encoding="utf-8") as f:
        f.write(CONTENT)
    print("[wolfssl-patch] wrote %s" % target)
else:
    print("[wolfssl-patch] SKIPPED — %s not found (wolfssl lib not installed yet; "
          "run pio pkg install first)" % os.path.dirname(target))
